### ISSUE TITLE
Lagging rainbow paths Nian cat

### ISSUE THREAD

**Issue by ivanoung** [shinglunwong/Canvas#2]
![staticshot_25-03-2018_12-01-21](https://user-images.githubusercontent.com/19902414/37871615-9b2f12d0-3024-11e8-8f75-c8225973cd6f.png)

**Comment by ivanoung** [comment]
That only happens when I draw'em fast, but it looks ok when I draw it slowly.

**Comment by didierkrux** [comment]
Not a bug ... just an awesome feature ;)
